[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<transmissor_esp32.cpp>
lib_deps =
    sandeepmistry/LoRa

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter = +<receptor_esp8266.cpp>
lib_deps =
    sandeepmistry/LoRa